### ISSUE TITLE
Сould not connect from WP8.1

### ISSUE THREAD

**Issue by rut4** [p3root/P3bble#4]
Hi.
I try to run the example in readme, but ```await pebbles[0].ConnectAsync();``` returns ```false``` every time.
This is my code:
```csharp
            var pebbles = await P3bble.P3bble.DetectPebbles();
            if (pebbles != null && pebbles.Count > 0)
            {
                bool connected = await pebbles[0].ConnectAsync();
                var message = String.Empty;
                if (connected)
                {
                    message = "connected to " + pebbles[0].DisplayName;
                }
                else
                {
                    message = "cannot connect";
                }
                var dialog = new MessageDialog(message);
                await dialog.ShowAsync();
            }
```

Of course I added into Package.appxmanifest the following code:
```xml
    <m2:DeviceCapability Name="bluetooth.rfcomm">
      <m2:Device Id="any">
        <m2:Function Type="serviceId:00001101-0000-1000-8000-00805f9b34fb" />
      </m2:Device>
    </m2:DeviceCapability>
```
Pebble AF57.
Do you have any ideas?
Thanks.

**Comment by p3root** [comment]
Do you have paired your pebble with your phone??

Von meinem Windows Phone gesendet
________________________________
Von: Eduard Paliy<mailto:notifications@github.com>
Gesendet: ‎14.‎02.‎2015 21:39
An: p3root/P3bble<mailto:P3bble@noreply.github.com>
Betreff: [P3bble] Сould not connect from WP8.1 (#4)

Hi.
I try to run example in readme, but ```await pebbles[0].ConnectAsync();``` returns ```false``` every time.
This is my code:
```csharp
            var pebbles = await P3bble.P3bble.DetectPebbles();
            if (pebbles != null && pebbles.Count > 0)
            {
                bool connected = await pebbles[0].ConnectAsync();
                var message = String.Empty;
                if (connected)
                {
                    message = "connected to " + pebbles[0].DisplayName;
                }
                else
                {
                    message = "cannot connect";
                }
                var dialog = new MessageDialog(message);
                await dialog.ShowAsync();
            }
```

Ofcourse I added into Package.appxmanifest the following code:
```xml
    <m2:DeviceCapability Name="bluetooth.rfcomm">
      <m2:Device Id="any">
        <m2:Function Type="serviceId:00001101-0000-1000-8000-00805f9b34fb" />
      </m2:Device>
    </m2:DeviceCapability>
```
Pebble AF57.
Do you have any ideas?
Thanks.

---
Reply to this email directly or view it on GitHub:
https://github.com/p3root/P3bble/issues/4

**Comment by rut4** [comment]
Yes, I have.

**Comment by rut4** [comment]
This pebble is in `pebbles` collection, but after this `bool connected = await pebbles[0].ConnectAsync();` the `connected` variable equals false.

**Comment by p3root** [comment]
Ok..
I need to look that up. Could you post your pebble version and phone version. But it will take a week, I am going on vacation tomorrow...

Von meinem Windows Phone gesendet
________________________________
Von: Eduard Paliy<mailto:notifications@github.com>
Gesendet: ‎14.‎02.‎2015 21:59
An: p3root/P3bble<mailto:P3bble@noreply.github.com>
Cc: Patrik Pfaffenbauer<mailto:patrik.pfaffenbauer@p3.co.at>
Betreff: Re: [P3bble] Сould not connect from WP8.1 (#4)

This pebble is in `pebbles` collection, but after this `bool connected = await pebbles[0].ConnectAsync();` the `connected` variable equals false.

---

**Comment by rut4** [comment]
Ok.

Pebble AF57
Firmware v2.9

Lumia 929 Denim
WP 8.1
OS version 8.10.14176

Thanks.

**Comment by rut4** [comment]
I found that exception throws in `P3bble.Communication.Protocol.CreateProtocolAsync()` while connecting to the pebble.
You can see this exception on the screen:
![image](https://cloud.githubusercontent.com/assets/2667321/6202541/7f3abd7c-b502-11e4-962f-0c7ce03c60e0.png)
So, I tried to use [flint library](https://github.com/barometz/flint) but I have the same error in the same place.

**Comment by rut4** [comment]
I have found a solution. Just replace service id by `00000000-deca-fade-deca-deafdecacaff`.
